import React from 'react';

const Section1 = () => {
    return (
        <div className='w-full m-10 min-h-screen'>
            <p className='font-bold font-Poppins'>DEVELOPMENT <span className='font-normal text-sm ml-4 text-[#999999]'>16 March 2023</span></p>
            <p className='font-audiowide text-4xl my-6 w-[900px] leading-relaxed text-[#262F68]'>How to make a Game look more attractive with New VR & AI Technology</p>
            <img className='w-[1200px] h-[600px]' src="https://s3-alpha-sig.figma.com/img/cd08/c550/4329d5e63cbe3fb18b46e3cc33bc385f?Expires=1734307200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=JJGxPmj-DZjqMMbzM2h3kjzxUyDQTQDvNAr3Ckub-6ulGaCecoKoEDCmttx567HIcdpgs1DBfthRjGXOTC0fgt00j~B4bYBvzW~SB4KgNfOFOXGGVOrSBWPtbyYUJWyloWrqqHRNDZU1NSV0xghwAkc5HtryAQejfk5RGcaE8gWUqN4hORvPmrW76C-y07PVrMRH4vaCl705nIerQwv8quL4fKo5mI-PsdsQGr-T4CDg9luXjoYBR9bQH96l88zFL9phj29G8m-7HUFzVkjy04tloTj-O-FPAALYmMPraPz8c2XD6iKMYekEcVo32~cSoGjY4B-Z6AiLILi0Tyh-9A__" alt="" />
            <p className='text-[#666666] w-[1100px] mx-2 my-6'>Google has been investing in AI for many years and bringing its benefits to individuals, businesses and communities. Whether it’s publishing state-of-the-art research, building helpful products or developing tools and resources that enable others, we’re committed to making AI accessible to everyone.
            We’re now at a pivotal moment in our AI journey. Breakthroughs in generative AI are fundamentally changing how people interact with technology — and at Google, we’ve been responsibly developing large language models so we can safely bring them to our products. Today, we’re excited to share our early progress. Developers and businesses can now try new APIs and products that make it easy, safe and scalable to start building with Google’s best AI models through Google Cloud and a new prototyping environment called MakerSuite. And in Google Workspace, we’re introducing new features that help people harness the power of generative AI to create, connect and collaborate.</p>
            <p className='text-[#666666] w-[1100px] mx-2 my-6'>Google has been investing in AI for many years and bringing its benefits to individuals, businesses and communities. Whether it’s publishing state-of-the-art research, building helpful products or developing tools and resources that enable others, we’re committed to making AI accessible to everyone.
            We’re now at a pivotal moment in our AI journey. Breakthroughs in generative AI are fundamentally changing how people interact with technology — and at Google, we’ve been responsibly developing large language models so we can safely bring them to our products. Today, we’re excited to share our early progress. Developers and businesses can now try new APIs and products that make it easy, safe and scalable to start building with Google’s best AI models through Google Cloud and a new prototyping environment called MakerSuite. And in Google Workspace, we’re introducing new features that help people harness the power of generative AI to create, connect and collaborate.</p>
           <div className='flex text-[#666666] justify-end w-full'> <p className='w-[700px] border-l-4 border-[#FCCF12] mr-20 font-Poppins px-4 py-2 flex gap-2 flex-col'>“People worry that computers will get too smart and take over the world, but the real problem is that they’re too stupid and they’ve already taken over the world.”
            <span className='text-black text-sm font-bold'>  – Pedro Domingos</span>
           </p>
           </div>
           <p className='text-[#666666] w-[1100px] mx-2 my-6'>More than 3 billion people already benefit from AI-powered features in Google Workspace, whether it’s using Smart Compose in Gmail or auto-generated summaries in Google Docs. Now, we’re excited to take the next step and bring a limited set of trusted testers a new set of features that makes the process of writing even easier. In Gmail and Google Docs, you can simply type in a topic you’d like to write about, and a draft will be instantly generated for you. So if you’re a manager onboarding a new employee, Workspace saves you the time and effort involved in writing that first welcome email. From there, you can elaborate upon or abbreviate the message or adjust the tone to be more playful or professional — all in just a few clicks. We’ll be rolling out these new experiences to testers in the coming weeks.</p>
           <img className='w-[800px] mx-auto h-[300px] rounded-lg' src="https://s3-alpha-sig.figma.com/img/7bb4/eaa2/08ac0d1cddd20941d00385afa51f4a7f?Expires=1734307200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=SUhNWzMsyC6RMWw-yLde6ar5cb8jvqECDe43IKaiOkfECjUQJ3NvuTNa-WRATtvGVCTxjOGdWQmXxJ9LHc~W0j5c1dK7-m5P~jK~Cto2ipzdrr~FaINO5Fro-X3wFl9e5TDHkOM8u8x7OsflHNsMhWWtps~xaNbnXJ-MSTKoRJHxVE3Gl7M47flO5iPZEEYCUt529Yrt1C1PbY1gXpnCN9d4jo-b5v5hJefg2kmMZUFdsBSytAFLOvmF93y7RKR0KY-YsoQS0xBthUhFBznfMDfy82H~jmHvVLMWxP9s~aU0xQbT0t6eJqTuuEaKQe5euuRA06GVum9A05sbsiugLg__" alt="" />
           <p className='my-10 w-[1100px] mx-2 tracking-widest font-Poppins'>We’re so excited by the potential of generative AI, and the opportunities it will unlock — from helping people express themselves creatively, to helping developers build brand new types of applications, to transforming how businesses and governments engage their customers and constituents. Stay tuned for more to come in the weeks and months ahead.</p>
        </div>
    );
};

export default Section1;